=== Cesio-organizzazione-di/ByteCourier2/XML/spedizioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="spedizioni">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="spedizione" maxOccurs = "unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name = "spedizione">
    <xs:complexType>
      <xs:sequence>
        <xs:element name = "id_spedizione" type = "xs:integer" />
        <xs:element name = "byteCourier1" type = "xs:string" />
        <xs:element name = "byteCourier2" type = "xs:string"/>
        <xs:element name = "destinatario" type = "profilo" />
        <xs:element name = "n_colli" type = "xs:integer" />
        <xs:element name = "tipo_collo" type = "collo" minOccurs = "1" maxOccurs = "unbounded" />
        <xs:element name = "onere" type = "xs:string" />
        <xs:element name = "ritiro" type = "indirizzo" />
		<xs:element name = "auto" type = "xs:string" />
      </xs:sequence>
      <xs:attribute name = "username" type = "xs:string" use = "required" />
      <xs:attribute name = "tipologia" type = "xs:integer" use = "required" />
      <xs:attribute name = "stato" type = "xs:string" default = "In sospeso">
        <xs:simpleType> 
          <xs:restriction base = "xs:string">
            <xs:enumeration value = "In sospeso" />
            <xs:enumeration value = "In carico" />
            <xs:enumeration value = "Consegnato" />
			<xs:enumeration value = "Rifiutato" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
   <xs:complexType name = "profilo">
      <xs:sequence>
        <xs:element ref = "nome"  />
        <xs:element ref = "indirizzo" />
        <xs:element ref = "telefono" />
      </xs:sequence>
    </xs:complexType>
    <xs:complexType name = "collo">
      <xs:sequence>
        <xs:element ref = "dimensione" />
        <xs:element ref = "peso" />
        <xs:element ref = "fragile" />
      </xs:sequence>
    </xs:complexType> 
    <xs:complexType name = "indirizzo">
      <xs:sequence>
        <xs:element ref = "via" />
        <xs:element ref = "n_civico" />
        <xs:element ref = "citta" />
        <xs:element ref = "CAP" />
      </xs:sequence>
    </xs:complexType>
    <complexType name = "dimensione">
      <xs:sequence>
       <xs:element ref = "altezza" />
       <xs:element ref = "larghezza" />
       <xs:element ref = "lunghezza" />
      </xs:sequence>
    </complexType>
	<xs:element ref = "nome" type = "xs:string" />
    <xs:element ref = "telefono" type = "xs:integer" />
    <xs:element name = "peso" type = "xs:integer" />
    <xs:element name = "fragile" type = "xs:string" />
    <xs:element name = "via" type = "xs:string" />
    <xs:element name = "n_civico" type = "xs:integer" />
    <xs:element name = "citta" type = "xs:string" />
    <xs:element name = "CAP" type = "xs:string" />
    <xs:element name = "altezza" type = "xs:integer" />
    <xs:element name = "larghezza" type = "xs:integer"/>
    <xs:element name = "lunghezza" type = "xs:integer" />
</xs:schema>

=== Cesio-organizzazione-di/ByteCourier2/XML/spedizioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<spedizioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spedizioni.xsd">
	<spedizione username="xrushofblood" tipologia="2" stato="In sospeso">
	<id_spedizione>1</id_spedizione>
	<byteCourier1/>
	<byteCourier2/>
	<destinatario>
		<nome>Simone Orelli</nome>
		<indirizzo>
			<via>Foresta</via>
			<n_civico>45</n_civico>
			<citta>Sezze</citta>
			<CAP>04110</CAP>
		</indirizzo>
		<telefono>3398767345</telefono>
	</destinatario>
	<n_colli>1</n_colli>
	<tipo_collo>
		<dimensione>
			<altezza>50</altezza>
			<larghezza>20</larghezza>
			<lunghezza>60</lunghezza>
		</dimensione>
		<peso>10</peso>
		<fragile>no</fragile>
	</tipo_collo>
	<onere>Mittente</onere>
	<ritiro>
		<via>Via Giovanniello</via>
		<n_civico>45</n_civico>
		<citta>Latina</citta>
		<CAP>04100</CAP>
	</ritiro>
	<auto>no</auto>
	</spedizione>
	<spedizione username="xrushofblood" tipologia="4" stato="In sospeso">
	<id_spedizione>2</id_spedizione>
	<byteCourier1/>
	<byteCourier2/>
	<destinatario>
		<nome>Simone Orelli</nome>
		<indirizzo>
			<via>Foresta</via>
			<n_civico>4</n_civico>
			<citta>Sezze</citta>
			<CAP>04110</CAP>
		</indirizzo>
		<telefono>3398767345</telefono>
	</destinatario>
	<n_colli>1</n_colli>
	<tipo_collo>
		<dimensione>
			<altezza>50</altezza>
			<larghezza>20</larghezza>
			<lunghezza>60</lunghezza>
		</dimensione>
		<peso>10</peso>
		<fragile>no</fragile>
	</tipo_collo>
	<onere>Mittente</onere>
	<ritiro/>
	<auto>no</auto>
	</spedizione>
	<spedizione username="xrushofblood" tipologia="1" stato="In sospeso">
	<id_spedizione>3</id_spedizione>
	<byteCourier1/>
	<byteCourier2/>
	<destinatario>
		<nome>Simone Orelli</nome>
		<indirizzo>
			<via>Foresta</via>
			<n_civico>5</n_civico>
			<citta>Sezze</citta>
			<CAP>04110</CAP>
		</indirizzo>
		<telefono>3398767345</telefono>
	</destinatario>
	<n_colli>1</n_colli>
	<tipo_collo>
		<dimensione>
			<altezza>50</altezza>
			<larghezza>20</larghezza>
			<lunghezza>60</lunghezza>
		</dimensione>
		<peso>10</peso>
		<fragile>no</fragile>
	</tipo_collo>
	<onere>Mittente</onere>
	<ritiro>
		<via>Via Giovanniello</via>
		<n_civico>45</n_civico>
		<citta>Latina</citta>
		<CAP>04100</CAP>
	</ritiro>
	<auto>no</auto>
	</spedizione>
	<spedizione username="orelli_srl" tipologia="3" stato="In sospeso">
	<id_spedizione>4</id_spedizione>
	<byteCourier1/>
	<byteCourier2/>
	<destinatario>
		<nome>Laura Stella</nome>
		<indirizzo>
			<via>Montagna</via>
			<n_civico>54</n_civico>
			<citta>Sezze</citta>
			<CAP>04110</CAP>
		</indirizzo>
		<telefono>3398736345</telefono>
	</destinatario>
	<n_colli>2</n_colli>
	<tipo_collo>
		<dimensione>
			<altezza>50</altezza>
			<larghezza>20</larghezza>
			<lunghezza>60</lunghezza>
		</dimensione>
		<peso>10</peso>
		<fragile>no</fragile>
	</tipo_collo>
	<onere>Destinatario</onere>
	<ritiro/>
	<auto>no</auto>
	</spedizione>
	<spedizione username="orelli_srl" tipologia="5" stato="In sospeso">
	<id_spedizione>5</id_spedizione>
	<byteCourier1/>
	<byteCourier2/>
	<destinatario>
		<nome>Laura Campagna</nome>
		<indirizzo>
			<via>Stella</via>
			<n_civico>54</n_civico>
			<citta>Sermoneta</citta>
			<CAP>04115</CAP>
		</indirizzo>
		<telefono>3398736335</telefono>
	</destinatario>
	<n_colli>3</n_colli>
	<tipo_collo>
		<dimensione>
			<altezza>50</altezza>
			<larghezza>20</larghezza>
			<lunghezza>60</lunghezza>
		</dimensione>
		<peso>10</peso>
		<fragile>si</fragile>
	</tipo_collo>
	<onere>Mittente</onere>
	<ritiro>
		<via>Via del Colosseo</via>
		<n_civico>101</n_civico>
		<citta>Roma</citta>
		<CAP>00100</CAP>
	</ritiro>
	<auto>no</auto>
	</spedizione>
</spedizioni>
