=== Cesio-organizzazione-di/ByteCourier2/XML/tipologie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pacchetti">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pacchetto" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name = "pacchetto">
    <xs:complexType>
      <xs:sequence>
        <xs:element name = "id_pacchetto" type = "xs:integer" />
        <xs:element name = "nome" type = "xs:string" />
        <xs:element name = "descrizione" type = "xs:string" />
        <xs:element name = "tempo_cons" type = "xs: string" />
        <xs:element name = "prezzo" type = "xs:decimal" />
      </xs:sequence>
      <xs:attribute name = "stato" type = "xs:string" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Cesio-organizzazione-di/ByteCourier2/XML/tipologie.xml
<?xml version="1.0" encoding="UTF-8"?>
<pacchetti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tipologie.xsd"><pacchetto><id_pacchetto>1</id_pacchetto><nome>Regular</nome><descrizione>L’opzione di spedizione più; economica per spedire pacchi e valigie a livello internazionale. L’opzione di spedizione Regular è ideale sia per spedizioni tra privati sia per le aziende che necessitano consegnare prodotti ai clienti.</descrizione><tempo_cons>3-7 giorni lavorativi</tempo_cons><prezzo>29.99</prezzo></pacchetto><pacchetto><id_pacchetto>2</id_pacchetto><nome>Express</nome><descrizione>Il servizio di spedizione Express è la tipologia di spedizione più rapida tra le diverse opzioni disponibili, in quanto prevede il trasporto via aerea. Questo tipo di spedizione è ideale per consegne urgenti ai propri clienti.</descrizione><tempo_cons>1-2 giorni lavorativi</tempo_cons><prezzo>44.89</prezzo></pacchetto><pacchetto><id_pacchetto>3</id_pacchetto><nome>Buste e Documenti</nome><descrizione>Servizio di spedizione dedicato alla spedizione di lettere, documenti cartacei e personali. Disponibile sia per privati sia per aziende.</descrizione><tempo_cons>1-3 giorni lavorativi</tempo_cons><prezzo>14.99</prezzo></pacchetto><pacchetto><id_pacchetto>4</id_pacchetto><nome>Cargo</nome><descrizione>La tipologia di spedizione ideale per il trasporto di articoli pesanti o di grandi dimensioni. Disponibile per aziende e privati.</descrizione><tempo_cons>2-7 giorni lavorativi</tempo_cons><prezzo>59.79</prezzo></pacchetto><pacchetto><id_pacchetto>5</id_pacchetto><nome>Camion</nome><descrizione>Ideale per il trasporto e la distribuzione di carichi ingombranti o pesanti. Trasporto diretto tramite camion dedicato interamente al tuo carico. Disponibile per le aziende.</descrizione><tempo_cons>1-6 giorni lavorativi</tempo_cons><prezzo>99.79</prezzo></pacchetto><pacchetto><id_pacchetto>6</id_pacchetto><nome>Prime</nome><descrizione>Ideale per trasporti periodici di merce leggera. Abbonati al servizio, scegli il giorno della settimana in cui verrà effettuata la spedizione e riceverai un lotto dedicato sul camion delle consegne.</descrizione><tempo_cons>24 ore nel giorno scelto</tempo_cons><prezzo>19.99</prezzo></pacchetto></pacchetti>
